## Algebra liniowa - biblioteki numeryczne 
W środowisku języka Python dostępne są dwie biblioteki numeryczne numpy i scipy. Dokumentacja: https://numpy.org/doc/, https://docs.scipy.org/doc/. Znajdź informacje wyjaśniające różnice między tymi bibliotekami. 

### Zadanie 1
Napisz krótki program, który wyświetli informację o wersji biblioteki oraz jej konfiguracji. Zwróć uwagę z jakich bibliotek numerycznych korzystają biblioteki Python'a

In [9]:
import numpy as np
print("-------------- Numpy Version : ------------ \n{}".format(np.__version__))
print("--------------------------------------------")
print("-------------- Numpy Configure : ------------ ")
print(np.show_config())
print("--------------------------------------------")


-------------- Numpy Version : ------------ 
1.18.1
--------------------------------------------
-------------- Numpy Configure : ------------ 
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None
--------------------------------------------


In [10]:
import scipy as sc
print("-------------- Scipy Version : ------------ \n{}".format(sc.__version__))
print("--------------------------------------------")
print("-------------- Scipy Configure : ------------ ")
print(sc.show_config())
print("--------------------------------------------")

-------------- Scipy Version : ------------ 
1.4.1
--------------------------------------------
-------------- Scipy Configure : ------------ 
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None
--------------------------------------------


### Zadanie 2 
Napisz program, który wyświetla wbudowaną pomoc dla funkcji: dodawanie wektorów, 

In [11]:
print(np.add.__doc__)
# lub
print(help(np.add))


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

### Zadanie 3
Napisz programy, które testują wektory danych pod kątem obecności elementów zerowych lub nieskończonych (sprawdź różne warianty takich funkcji). 
Napisz program porównujące wektory i macierze (według wartości elementów).

In [12]:
def is_zero(vector):
    #np.where(vector == 0) wyświetli tablicę indeksów dla których wartości tablicy vector będą równe 0
    print(np.where(vector == 0))
    #np.nonzero(vector) wyświetli tablicę indeksów dla których wartości tablicy vector będą różne od 0
    print(np.nonzero(vector))
    #np.argwhere działa podobnie jak np.where
    print(np.argwhere(vector == 0))


def is_inf(vector):
    #np.where(vector == np.inf) wyświetli tablicę indeksów dla których wartości tablicy vector będą równe inf
    print(np.where(vector == np.inf))
    #np.isinf(vector) wyświetli tablicę booli jeśli wartości odpowiedniej współrzędnek z vectora jest równa inf to w tablicu wynikowej pojawi się true jeśli nie to false 
    print(np.isinf(vector))
     #np.argwhere działa podobnie jak np.where
    print(np.argwhere(vector == np.inf))
    


def is_equal(array_a, array_b):
    print("First array :\n{}".format(array_a))
    print("Second array :   \n{}".format(array_b))
    print("Which cells are equals?  : \n{}".format(np.equal(array_a, array_b)))


matrix_a = np.matrix('1 2; 3 4; 2 3')
matrix_b = np.matrix('1 2; 2 4; 2 3')
matrix_c = np.matrix('1 2; 3 4; 2 3')
vector_a = np.array([1, 2, 3, 4, np.inf])
vector_b = np.array([1, 2, 3, 4, 0])
vector_c = np.array([2, 2, 4, 4, np.inf])

print("-------------Is Equal?--------------")
is_equal(matrix_a, matrix_b)
is_equal(vector_a, vector_b)
print("-----------------------------------")
print("-------------Is Zero?--------------")
is_zero(vector_b)
print("-----------------------------------")
print("-------------Is Inf?---------------")
is_inf(vector_a)
print("-----------------------------------")


-------------Is Equal?--------------
First array :
[[1 2]
 [3 4]
 [2 3]]
Second array :   
[[1 2]
 [2 4]
 [2 3]]
Which cells are equals?  : 
[[ True  True]
 [False  True]
 [ True  True]]
First array :
[ 1.  2.  3.  4. inf]
Second array :   
[1 2 3 4 0]
Which cells are equals?  : 
[ True  True  True  True False]
-----------------------------------
-------------Is Zero?--------------
(array([4]),)
(array([0, 1, 2, 3]),)
[[4]]
-----------------------------------
-------------Is Inf?---------------
(array([4]),)
[False False False False  True]
[[4]]
-----------------------------------


### Zadanie 4 
Napisz program, który wylicza ile danych w bajtach zajmuje wektor lub macierz

In [13]:
def array_size(array):
    print(array.nbytes)


array_size(matrix_b)
array_size(vector_a)

48
40


### Zadanie 5
Napisz kilka programów, które demonstrują jak można w numpy tworzyć wektory i macierze wypełnione różnymi danymi lub mającymi pewną szczególną postać, np. , danymi losowymi, danymi z podanego zakresy, macierze identyczności, ... 

In [14]:
#Tworzy wektor o podanym rozmiarze size oraz liczby będą losowane z zakresu [min, max]
def create_rand_vector(min, max, size):
    return np.random.randint(low=min, high=max+1, size=(size,))


#Tworzy macierz o podanym rozmiarze cols na rows oraz liczby będą losowane z zakresu [min, max]
def create_rand_matrix(min, max, cols, rows):
    return np.random.randint(low=min, high=max + 1, size=(rows, cols))


#Tworzy macierz identyczności o podanym rozmiarze size
def create_identity_matrix(size):
    return np.identity(size, dtype=None)


#Tworzy miacierz odwrotną do podanej
def create_inverse_matrix(matrix):
    return np.linalg.inv(matrix)


print(create_rand_vector(9, 10, 20))
print(create_rand_matrix(9, 15, 3, 5))
print(create_identity_matrix(5))
print(create_inverse_matrix(create_rand_matrix(3, 10, 3, 3)))
print(create_inverse_matrix(create_identity_matrix(5)))

[10 10  9  9  9  9  9  9  9  9 10  9  9  9 10 10  9  9 10  9]
[[11  9 12]
 [15 12 13]
 [13 10 15]
 [10 12 12]
 [13 15 15]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[-5.          2.          4.        ]
 [ 1.4        -0.6        -1.        ]
 [ 3.66666667 -1.33333333 -3.        ]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Zadania 6
Napisz programy wykonujący podstawowe operacje algebry: dodawanie wektórów, mnożenie wektorów, mnożenia macierzy. Najpierw napisz je w wersji szkolnej, nie zastanawiając się nad jakąkolwiek optymalizacją. Następnie spróbuj zmienić organizację obliczeń tak by uzyskać poprawę wydajności. Na koniec porównaj swoje metody do dedykowanych funkcji z bibliotek NumPy i SciPy. 


In [15]:
import time
from tabulate import tabulate


def sum_of_vectors_simple_sol(vector_a, vector_b):
    start = time.time()
    result = []
    index = 0
    for value in vector_a:
        result.append(value + vector_b[index])
        index += 1
    end = time.time()
    return result, end - start


def product_of_vector_simple_sol(vector_a, vector_b):
    start = time.time()
    result = 0
    index = 0
    for value in vector_a:
        result += value * vector_b[index]
        index += 1
    end = time.time()
    return result, end-start


def product_of_matrix_simple_sol(matrix_a, matrix_b):
    start = time.time()
    num_rows_a, num_cols_a = matrix_a.shape
    num_rows_b, num_cols_b = matrix_b.shape
    result = np.zeros((num_rows_a, num_cols_b))
    for i in range(num_rows_a):
        for j in range(num_cols_b):
            for k in range(num_rows_b):
                result[i][j] += matrix_a[i][k] * matrix_b[k][j]
    end = time.time()
    return result, end-start


def sum_of_vectors_numpy(vector_a, vector_b):
    start = time.time()
    result = np.add(vector_a, vector_b)
    end = time.time()
    return result, end - start


def product_of_vector_numpy(vector_a, vector_b):
    start = time.time()
    result = np.dot(vector_a, vector_b)
    end = time.time()
    return result, end - start


def product_of_matrix_numpy(matrix_a, matrix_b):
    start = time.time()
    result = np.dot(matrix_a, matrix_b)
    end = time.time()
    return result, end-start


vector_a = np.array([2, 2, 4, 4, 2])
vector_b = np.array([1, 2, 3, 4, 0])
vector_c = np.array([1, 2])
vector_d = np.array([3, -5])
matrix_a = np.array([[12, 7, 3], [4, 5, 6], [7, 8, 9]])
matrix_b = np.array([[5, 8, 1, 2], [6, 7, 3, 0], [4, 5, 9, 1]])


output = [
        ['Sum of vectors (Simple solution) : ', sum_of_vectors_simple_sol(vector_a, vector_b)[0], sum_of_vectors_simple_sol(vector_a, vector_b)[1]],
        ['Sum of vectors (Numpy) : ', sum_of_vectors_numpy(vector_a, vector_b)[0], sum_of_vectors_numpy(vector_a, vector_b)[1]],
        ['Product of vectors (Simple solution) : ', product_of_vector_simple_sol(vector_a, vector_b)[0], product_of_vector_simple_sol(vector_a, vector_b)[1]],
        ['Product of vectors (Numpy) : ', product_of_vector_numpy(vector_a, vector_b)[0], product_of_vector_numpy(vector_a, vector_b)[1]],
        ['Product of matrix (Simple solution) : ',  product_of_matrix_simple_sol(matrix_a, matrix_b)[0], product_of_matrix_simple_sol(matrix_a, matrix_a)[1]],
        ['Product of matrix (Numpy) : ',  product_of_matrix_numpy(matrix_a, matrix_b)[0], product_of_matrix_numpy(matrix_a, matrix_a)[1]]
        ]

print(tabulate(output, headers=['L.P.', 'Value', 'Execute time '], tablefmt="fancy_grid"))

╒════════════════════════════════════════╤═════════════════════════╤═════════════════╕
│ L.P.                                   │ Value                   │   Execute time  │
╞════════════════════════════════════════╪═════════════════════════╪═════════════════╡
│ Sum of vectors (Simple solution) :     │ [3, 4, 7, 8, 2]         │     5.24521e-06 │
├────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ Sum of vectors (Numpy) :               │ [3 4 7 8 2]             │     1.43051e-06 │
├────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ Product of vectors (Simple solution) : │ 34                      │     6.19888e-06 │
├────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ Product of vectors (Numpy) :           │ 34                      │     7.15256e-06 │
├────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ Product of matrix (Simple solution) :  │ 

Z powyższej tabelki wynika, że dla każdej operacji biblioteka jest szybsza.